apiVersion: v1
kind: ConfigMap
metadata:
  name: nibiru-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  application.properties: |-
      application.url=api
      camel.servlet.mapping.context-path=/nibiru/*
      server.port=4000
      spring.main.sources=org.rutebanken.nibiru
      destination.url=http://localhost:3000/v1
      logging.level.org.rutebanken.nibiru=INFO
      processor.map.counties.enabled=true
      server.shutdown=graceful
      spring.lifecycle.timeout-per-shutdown-phase=45s
      management.server.port=9001
      management.endpoints.enabled-by-default=false
      management.endpoint.info.enabled=true
      management.endpoint.health.enabled=true
      management.endpoint.prometheus.enabled=true
      management.endpoint.health.group.liveness.show-details=always
      management.endpoint.health.group.readiness.show-details=always
      management.endpoints.web.exposure.include=info,health,prometheus,env,metrics
      management.metrics.enable.all=false
      management.metrics.enable.jvm=true
      management.metrics.enable.http=true
      management.metrics.enable.app=true
      management.metrics.distribution.percentiles-histogram.http.server.requests=true
      camel.metrics.uriTagEnabled=true
      camel.metrics.uri-tag-dynamic=true
