apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  maxReplicas:  {{ .Values.horizontalPodAutoscaler.maxReplicas | default "2" }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas | default "1" }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app.name" . }}
  targetCPUUtilizationPercentage: {{ .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage | default "80" }}