replicas: 3
gcpBasePath: gs://ror-kakka-production/es-data/
ingress:
  enabled: true
  domainName: .entur.io

horizontalPodAutoscaler:
  maxReplicas: 10
  minReplicas: 5
  targetCPUUtilizationPercentage: 80


PodDisruptionBudget:
  minAvailable: 80%
