version: 2
aliases:
  - &install-dependencies
    name: Install Node Dependencies
    command: npm install
  - &test
    name: Test
    command: npm run test
  - &GCP-auth
    name: GCP Authenticate
    command: |
      echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
      /tools/gcp_authenticate.sh
  - &docker-login
    name: Docker login
    command: |
      docker login -u _json_key --password-stdin https://eu.gcr.io <<< "${DOCKER_PASSWORD}"
  - &docker-build-and-push
    name: Docker build and push
    command: |
      IMAGE="eu.gcr.io/entur-system-1287/${CIRCLE_PROJECT_REPONAME}"
      echo "Image: ${IMAGE}"
      docker build -t $IMAGE .
      docker tag $IMAGE "${IMAGE}":"${VERSION}"
      docker push $IMAGE
    environment:
      CIRCLE_PROJECT_REPONAME: "pelias"
  - &save-dependency-cache
    paths:
      - node_modules
    key: node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
  - &restore-dependency-cache
    name: Restore dependency cache
    keys:
      - node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
  - &tag-git-version
    name: Tag git commit with build version and push to github
    command: |
      git config --global user.email "circleci@entur.no"
      git config --global user.name "circleci"
      git tag $VERSION
      git push origin $VERSION
  - &create-image-version
    name: Create new image version and store to env var and as file in workspace
    command: |
          echo "export VERSION=$CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)"  >> $BASH_ENV
jobs:
  install:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: *install-dependencies
      - save-cache: *save-dependency-cache
  test:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore-cache: *restore-dependency-cache
      - run: *test
  docker-build:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore-cache: *restore-dependency-cache
      - *create-image-version
      - *tag-git-version
      - run: *GCP-auth
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *docker-login
      - run: *docker-build-and-push
workflows:
  version: 2
  install-test-build-deploy:
    jobs:
      - install:
          context: org-carbon
      - test:
          context: org-carbon
          requires:
            - install
      - docker-build:
          context: org-carbon
          requires:
            - test
          filters:
            branches:
              only:
              - master
