version: 2
aliases:
  - &install-dependencies
    name: Install Node Dependencies
    command: npm install
  - &test
    name: Test
    command: npm run test
  - &google-sdk-container-config
    docker:
      - image: google/cloud-sdk:latest
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
  - &GCP-auth-docker
    name: GCP authentication with docker
    command: |
      echo $DOCKER_PASSWORD > ${HOME}/account-auth.json
  - &docker-build-and-push
    name: Docker build and push
    command: |
      IMAGE="eu.gcr.io/entur-system-1287/${CIRCLE_PROJECT_REPONAME}"
      echo "Image: ${IMAGE}"
      docker build -t $IMAGE .
      docker tag $IMAGE "${IMAGE}":"${VERSION}"
      docker login -u _json_key --password-stdin https://eu.gcr.io < ${HOME}/account-auth.json
      docker push "${IMAGE}":"${VERSION}"
    environment:
      CIRCLE_PROJECT_REPONAME: "pelias"
  - &save-dependency-cache
    paths:
      - node_modules
    key: node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
  - &restore-dependency-cache
    name: Restore dependency cache
    keys:
      - node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
  - &tag-git-version
    name: Tag git commit with build version and push to github
    command: |
      git config --global user.email "circleci@entur.no"
      git config --global user.name "circleci"
      git tag $VERSION
      git push origin $VERSION
  - &create-image-version
    name: Create new image version and store to env var and as file in workspace
    command: |
          echo "export VERSION=$CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)"  >> $BASH_ENV
jobs:
  install-and-test:
    docker:
      - image: cimg/node:12.22.2
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: *install-dependencies
      - save-cache: *save-dependency-cache
      - run: *test
  docker-build:
    <<: *google-sdk-container-config
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - attach_workspace:
          at: ~/project
      - run: *GCP-auth-docker
      - checkout
      - restore-cache: *restore-dependency-cache
      - run: *create-image-version
      - run: *tag-git-version
      - run: *docker-build-and-push
workflows:
  version: 2
  install-test-build-deploy:
    jobs:
      - install-and-test:
          context: global
      - docker-build:
          context: global
          requires:
            - install-and-test
          filters:
            branches:
              only:
              - master
