env: dev

replicas: 5


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

resources:
  cpuLimit: 800m
  memLimit: 750Mi
  cpuRequest: 200m
  memRequest: 500Mi


image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

secondaryImage:
  identifier: eu.gcr.io/entur-system-1287/es-static-v2:0.0.2
  imagePullPolicy: Always
  containerPort: 9200
  resources:
    cpuLimit: '2'
    memLimit: 1500Mi
    cpuRequest: 600m
    memRequest: 1000Mi

secretMount:
  name: pelias-key
  mountPath: /etc/pelias/
  secretName: ror-pelias-sa-key
  readOnly: true

service:
  http:
    externalPort: 80
    internalPort: 3000
