env: dev

replicas: 1


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

PodDisruptionBudget:
  minAvailable: 50%

resources:
  memLimit: 750Mi
  cpuRequest: 650m
  memRequest: 500Mi

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always
secondaryImage:
  identifier: eu.gcr.io/entur-system-1287/es-static:master.20250211-SHA3a05782
  imagePullPolicy: Always
  containerPort: 9200
  resources:
    memLimit: 2000Mi
    cpuRequest: 1200m
    memRequest: 1500Mi
nibiruImage:
  identifier: eu.gcr.io/entur-system-1287/nibiru:master.20251031-SHAf28c7c9
  imagePullPolicy: Always
  containerPort: 4000
  healthPort: 9001
  resources:
    memLimit: 750Mi
    cpuRequest: 650m
    memRequest: 500Mi
    xmx: 1500m

service:
  http:
    externalPort: 80
    internalPort: 3000
    internalPortNibiru: 4000

horizontalPodAutoscaler:
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
