env: dev

replicas: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

resources:
  memLimit: 100Mi
  cpuRequest: 300m
  memRequest: 100m

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always
secondaryImage:
  identifier: eu.gcr.io/entur-system-1287/es-static:2.0.9
  imagePullPolicy: Always
  containerPort: 9200
  resources:
    memLimit: 1600Mi
    cpuRequest: 500m
    memRequest: 1600Mi
secretMount:
  name: pelias-key
  mountPath: /etc/pelias/credentials.json
  subPath: credentials.json
  secretName: ror-pelias-sa-key
  readOnly: true

service:
  http:
    externalPort: 80
    internalPort: 3000

rbac:
  enabled: false

enableRailReplacementBusFilter: false

horizontalPodAutoscaler:
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
