env: production
replicas: 3
gcpBasePath: gs://kakka-production/es-data/

cronjobRedeployPelias:
  enabled: true
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  environmentValues:
    cloudsdkCoreProject: entur-1287
    slackName: ror-prod-slack-url
  resources:
    cpuLimit: 900m
    memLimit: 2550Mi
    cpuRequest: 100m
    memRequest: 1000m
  image:
    repo: eu.gcr.io/entur-system-1287/deployment-rollout-restart:0.1.0
rbac:
  enabled: true

horizontalPodAutoscaler:
  maxReplicas: 6
  minReplicas: 3
  targetCPUUtilizationPercentage: 80
